//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoZilya.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public Nullable<int> IDUnit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> MaxSale { get; set; }
        public Nullable<int> IDManufacture { get; set; }
        public Nullable<int> IDSaller { get; set; }
        public Nullable<int> IDCategoriya { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Categoriya Categoriya { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        public virtual Saller Saller { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
